source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'InAction' do
    pod 'Alamofire', '~> 4.5'
    pod 'KeychainAccess', '~> 3.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'SwifterSwift’, ‘~> 4.2.0’

end